// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhthiKOvS8tVN541WIDijngbqOhuwUsXQ',
    appId: '1:956973659051:web:30323fc97082901cd258ee',
    messagingSenderId: '956973659051',
    projectId: 'chat-app-review-95585',
    authDomain: 'chat-app-review-95585.firebaseapp.com',
    storageBucket: 'chat-app-review-95585.appspot.com',
    measurementId: 'G-DE4PZ56PW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6eq1wslruJhwgIQ3eD-VVfIb23bFJhU',
    appId: '1:956973659051:android:ff54e9de36494a9bd258ee',
    messagingSenderId: '956973659051',
    projectId: 'chat-app-review-95585',
    storageBucket: 'chat-app-review-95585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJ3Wx7KBZgBLeTa_85H8HfED5qvWi9wY',
    appId: '1:956973659051:ios:d6f96193caf0a4dad258ee',
    messagingSenderId: '956973659051',
    projectId: 'chat-app-review-95585',
    storageBucket: 'chat-app-review-95585.appspot.com',
    iosBundleId: 'com.example.newStartReview2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJ3Wx7KBZgBLeTa_85H8HfED5qvWi9wY',
    appId: '1:956973659051:ios:d6f96193caf0a4dad258ee',
    messagingSenderId: '956973659051',
    projectId: 'chat-app-review-95585',
    storageBucket: 'chat-app-review-95585.appspot.com',
    iosBundleId: 'com.example.newStartReview2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhthiKOvS8tVN541WIDijngbqOhuwUsXQ',
    appId: '1:956973659051:web:39f277c135ec8d50d258ee',
    messagingSenderId: '956973659051',
    projectId: 'chat-app-review-95585',
    authDomain: 'chat-app-review-95585.firebaseapp.com',
    storageBucket: 'chat-app-review-95585.appspot.com',
    measurementId: 'G-WM55VRNWHT',
  );

}